/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Control.Control;
import java.awt.Color;
import javax.swing.JPanel;
import java.awt.*;
import javax.swing.*;


/**
 *
 * @author juanl
 */
public class Carrito2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Carrito2.class.getName());
    private final Control control;
    private JPanel panelLista;
    
    /**
     * Creates new form Carrito2
     */
    public Carrito2(Control control) {
        initComponents();
        this.control = control;

        setSize(400,650);
        getContentPane().setBackground(new Color(77,214,139));

        mostrarProductosFake(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrega = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEntrega.setText("Formas de entregas");
        btnEntrega.addActionListener(this::btnEntregaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnEntrega)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(btnEntrega)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregaActionPerformed
       control.mostrarSeleccionMetodoEntrega();
    }//GEN-LAST:event_btnEntregaActionPerformed

    private void mostrarProductosFake(){

        getContentPane().setLayout(new BorderLayout());

        panelLista = new JPanel();
        panelLista.setBackground(new Color(77,214,139));
        panelLista.setLayout(new BoxLayout(panelLista,BoxLayout.Y_AXIS));

        panelLista.add(crearItem("Bagel","$70.00"));
        panelLista.add(crearItem("Frappe","$50.00"));

        JScrollPane scroll = new JScrollPane(panelLista);
        scroll.setBorder(null);

        add(scroll,BorderLayout.CENTER);
        add(btnEntrega,BorderLayout.SOUTH);
    }
    
    private JPanel crearItem(String nombre,String precio){

        JPanel item = new JPanel(new BorderLayout());
        item.setBackground(new Color(77,214,139));
        item.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));

        JLabel img = new JLabel("IMG");
        img.setPreferredSize(new Dimension(80,80));
        img.setHorizontalAlignment(SwingConstants.CENTER);
        img.setBorder(BorderFactory.createLineBorder(Color.GRAY));

        item.add(img,BorderLayout.WEST);

        JPanel info = new JPanel();
        info.setBackground(new Color(77,214,139));
        info.setLayout(new BoxLayout(info,BoxLayout.Y_AXIS));

        info.add(new JLabel(nombre));
        info.add(new JLabel(precio));

        item.add(info,BorderLayout.CENTER);

        JPanel controles = new JPanel();
        controles.setBackground(new Color(77,214,139));

        controles.add(new JButton("🗑"));
        controles.add(new JButton("-"));
        controles.add(new JLabel("1"));
        controles.add(new JButton("+"));

        item.add(controles,BorderLayout.EAST);

        return item;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Carrito2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrega;
    // End of variables declaration//GEN-END:variables

    private PopupMenu Producto(String frappe, String $5000, String frappejpg) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
