//package GUI;
//
//import Control.Control;
//import GoOrderDTO.ProductoDTO;
//import GoOrderDTO.CostoDTO;
//import org.example.CalcularCostoCasoDeUso;
//import org.example.CostoServicio;
//
//import java.util.List;
//import org.example.CalcularCostoCasoDeUso;
//import org.example.CostoServicio;
//
//public class CostoFORM extends javax.swing.JFrame {
//
//    private Control control;
//    private CalcularCostoCasoDeUso useCase;
//
//    public CostoFORM(Control control) {
//        this.control = control;
//
//        useCase = new CalcularCostoCasoDeUso(
//                new CostoServicio()
//        );
//
//        initComponents();
//        eventos();
//        actualizarCosto();
//        mostrarProductos();
//    }
//
//    private void eventos() {
//
//        btnAplicarDescuento.addActionListener(e -> {
//            control.mostrarCodigoDescuento();
//            this.dispose();
//        });
//
//        btnFormaDePago.addActionListener(e -> {
//            control.mostrarFormaPago();
//            this.dispose();
//        });
//    }
//
//    private void actualizarCosto() {
//
//        List<ProductoDTO> productos = control.getCarrito();
//        double descuento = control.getDescuento();
//
//        CostoDTO costo = casoDeUso.ejecutar(productos, descuento);
//
//        lblValorSu.setText("$" + costo.getSubtotal());
//        lblValorIVA.setText("$" + costo.getIva());
//        lblDescuentoValor.setText("-$" + costo.getDescuento());
//        txtValorCosto.setText("$" + costo.getTotal());
//    }
//
//    private void mostrarProductos() {
//
//        List<ProductoDTO> productos = control.getCarrito();
//
//        int y = 20;
//
//        for (ProductoDTO p : productos) {
//
//            javax.swing.JLabel lbl = new javax.swing.JLabel(
//                    p.getNombre() + " - $" + p.getPrecio()
//            );
//
//            lbl.setBounds(20, y, 300, 20);
//
//            jPanel1.add(lbl);
//
//            y += 25;
//        }
//
//        jPanel1.repaint();
//    }
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        txtValorCosto = new javax.swing.JLabel();
//        lblTotal = new javax.swing.JLabel();
//        lblIVA = new javax.swing.JLabel();
//        lblValorIVA = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        lblDescuentoValor = new javax.swing.JLabel();
//        lblSubtotal = new javax.swing.JLabel();
//        lblValorSu = new javax.swing.JLabel();
//        btnAplicarDescuento = new javax.swing.JButton();
//        btnFormaDePago = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setBackground(new java.awt.Color(0, 204, 204));
//
//        txtValorCosto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        txtValorCosto.setText("jLabel1");
//
//        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        lblTotal.setText("Total:");
//
//        lblIVA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        lblIVA.setText("IVA:");
//
//        lblValorIVA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        lblValorIVA.setText("jLabel1");
//
//        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        jLabel2.setText("Descuento:");
//
//        lblDescuentoValor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        lblDescuentoValor.setText("jLabel3");
//
//        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        lblSubtotal.setText("Subtotal:");
//
//        lblValorSu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        lblValorSu.setText("jLabel3");
//
//        btnAplicarDescuento.setText("Aplicar Descuento");
//
//        btnFormaDePago.setText("Forma de Pago");
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                            .addComponent(lblTotal)
//                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                            .addComponent(txtValorCosto))
//                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
//                            .addComponent(lblIVA)
//                            .addGap(66, 66, 66)
//                            .addComponent(lblValorIVA)))
//                    .addGroup(jPanel1Layout.createSequentialGroup()
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jLabel2)
//                            .addComponent(lblSubtotal))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(lblValorSu)
//                            .addComponent(lblDescuentoValor))))
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addContainerGap(268, Short.MAX_VALUE)
//                .addComponent(btnFormaDePago)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(btnAplicarDescuento)
//                .addContainerGap())
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addContainerGap(196, Short.MAX_VALUE)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(lblSubtotal)
//                    .addComponent(lblValorSu))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel2)
//                    .addComponent(lblDescuentoValor))
//                .addGap(44, 44, 44)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(lblIVA)
//                    .addComponent(lblValorIVA))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(lblTotal)
//                    .addComponent(txtValorCosto))
//                .addGap(20, 20, 20)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(btnAplicarDescuento)
//                    .addComponent(btnFormaDePago))
//                .addContainerGap())
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CostoFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CostoFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CostoFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CostoFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CostoFORM().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton btnAplicarDescuento;
//    private javax.swing.JButton btnFormaDePago;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JLabel lblDescuentoValor;
//    private javax.swing.JLabel lblIVA;
//    private javax.swing.JLabel lblSubtotal;
//    private javax.swing.JLabel lblTotal;
//    private javax.swing.JLabel lblValorIVA;
//    private javax.swing.JLabel lblValorSu;
//    private javax.swing.JLabel txtValorCosto;
//    // End of variables declaration//GEN-END:variables
//}
